
goog.provide('urlbuilder.EventHandler');
goog.provide('urlbuilder.EventHandler.EventType');
goog.provide('urlbuilder.UrlEvent');

goog.require('goog.array');
goog.require('goog.events');
goog.require('goog.events.EventTarget');
goog.require('goog.events.Event');
goog.require('goog.object');
goog.require('goog.string');
goog.require('urlbuilder.UI');

/**
 * Handlers class.
 * @constructor
 */
urlbuilder.EventHandler = function(elements, actions)
{
  goog.events.EventTarget.call(this);
};
goog.inherits(urlbuilder.EventHandler, goog.events.EventTarget);

/**
 * Activate the listeners on the DOM elements.
 * @param {Array.<HTMLElement>} elements The input elements.
 */
urlbuilder.EventHandler.prototype.init = function(elements)
{
  goog.array.forEach(elements, function(element)
  {
    var id = element['id'];
    if(goog.string.startsWith(id, urlbuilder.UI.PREFIX))
    {
      var elementName = goog.string.remove(id, urlbuilder.UI.PREFIX).toUpperCase();
      goog.object.forEach(urlbuilder.EventHandler[elementName], function(handler, eventName)
      {
        goog.events.listen(element, eventName, handler, false, this);
      }, this);
    }
  }, this);
};

/**
 * Handlers for the URL text field.
 */
urlbuilder.EventHandler.URL = {
  'input': function(evt) {
    this.onUrlInput_(evt);
  }
};

/**
 * Handlers for the scheme text field.
 */
urlbuilder.EventHandler.SCHEME = {
  'input': function(evt) {
    this.onFieldInput_(evt);
  }
};

/**
 * Handlers for the domain text field.
 */
urlbuilder.EventHandler.DOMAIN = {
  'input': function(evt) {
    this.onFieldInput_(evt);
  }
};

/**
 * Handlers for the port text field.
 */
urlbuilder.EventHandler.PORT = {
  'input': function(evt) {
    this.onFieldInput_(evt);
  }
};

/**
 * Handlers for the path text field.
 */
urlbuilder.EventHandler.PATH = {
  'input': function(evt) {
    this.onFieldInput_(evt);
  }
};

/**
 * Default input behavior for a text field.
 * @param {Event} evt The event object.
 */
urlbuilder.EventHandler.prototype.onFieldInput_ = function(evt)
{
  
};

/**
 * Default input behavior for the url field.
 * @param {Event} evt The event object.
 */
urlbuilder.EventHandler.prototype.onUrlInput_ = function(evt)
{
  var target = evt['target'];
  var url = target['value'];
  var urlEvent = new urlbuilder.UrlEvent(url, target);
  this.dispatchEvent(urlEvent);
};

/**
 * The events generated by the interface.
 */
urlbuilder.EventHandler.EventType = {
  URL: 'url',
  FIELD: 'field'
};

/**
 * The event generated when a url is received.
 * @constructor
 */
urlbuilder.UrlEvent = function(url, target)
{
  goog.events.Event.call(this);

  this.type = urlbuilder.EventHandler.EventType.URL;
  this.target = target;
  this.url = url;
};
goog.inherits(urlbuilder.UrlEvent, goog.events.Event);

/**
 * The url.
 * @type {string}
 */
urlbuilder.UrlEvent.prototype.url = '';

